# Generated by Django 3.2.9 on 2021-12-21 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0002_auto_20211221_0737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighbourHood',
            new_name='NeighborHood',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
