# Generated by Django 3.2.9 on 2021-12-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20211221_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
