# Generated by Django 3.2.9 on 2021-12-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_alter_neighborhood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
