# Generated by Django 2.2.24 on 2022-01-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0007_auto_20220103_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
