# Generated by Django 2.2.24 on 2022-01-04 08:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0008_auto_20220104_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='content',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
