# Generated by Django 2.2.24 on 2022-01-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0010_auto_20220104_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
    ]
