# Generated by Django 2.2.24 on 2022-01-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0021_auto_20220106_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
