# Generated by Django 2.2.24 on 2022-01-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0022_auto_20220107_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='health_cell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_hotline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
