# Generated by Django 2.2.24 on 2022-01-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0023_auto_20220107_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='admin',
            new_name='user',
        ),
    ]
