# Generated by Django 2.2.24 on 2022-01-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0027_auto_20220107_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='photo',
        ),
    ]
