# Generated by Django 2.2.24 on 2022-01-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0030_auto_20220108_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.NeighborHood'),
        ),
    ]
